name: Test Action
run-name: ${{ gitea.actor }} is testing out Gitea Actions
on:
    push:
        branches:
            - main
            - develop
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    UI-Build-&-Test:
        runs-on: local-runner
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: |
                    . $NVM_DIR/nvm.sh
                    cd ui
                    nvm install
                    npm install
                    npm run eslint
                    npm run build
            - name: Test
              run: |
                    . $NVM_DIR/nvm.sh
                    cd ui
                    nvm install
                    npm run test
                    npm run test:coverage
    SRV-Build-&-Test:
        runs-on: local-runner
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: |
                    . $NVM_DIR/nvm.sh
                    cd server
                    nvm install
                    npm install
                    npm run eslint
                    npm run build
    DEV-Build-Docker:
        runs-on: local-runner
        needs: [UI-Build-&-Test, SRV-Build-&-Test]
        if: gitea.ref_name == develop
        env:
            BUILD_NUMBER: ${{ gitea.run_id }}
        steps:
            - uses: actions/checkout@v3
            - name: UI Docker Build
              run: |
                    cd ui
                    docker build -t git.aru-software.pl/aru-software/as-wiki/as-wiki-ui:latest-dev -t git.aru-software.pl/aru-software/as-wiki/as-wiki-ui:0.0.$BUILD_NUMBER-dev .
                    docker login git.aru-software.pl -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
                    docker push git.aru-software.pl/aru-software/as-wiki/as-wiki-ui:latest-dev
                    docker push git.aru-software.pl/aru-software/as-wiki/as-wiki-ui:0.0.$BUILD_NUMBER-dev
            - name: SRV Docker Build
              run: |
                    cd server
                    docker build -t git.aru-software.pl/aru-software/as-wiki/as-wiki-srv:latest-dev -t git.aru-software.pl/aru-software/as-wiki/as-wiki-srv:0.0.$BUILD_NUMBER-dev .
                    docker login git.aru-software.pl -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
                    docker push git.aru-software.pl/aru-software/as-wiki/as-wiki-srv:latest-dev
                    docker push git.aru-software.pl/aru-software/as-wiki/as-wiki-srv:0.0.$BUILD_NUMBER-dev
    PROD-Build-Docker:
        runs-on: local-runner
        needs: [UI-Build-&-Test, SRV-Build-&-Test]
        if: gitea.ref_name == main
        env:
            BUILD_NUMBER: ${{ gitea.run_id }}
        steps:
            - uses: actions/checkout@v3
            - name: UI Docker Build
              run: |
                    cd ui
                    docker build -t git.aru-software.pl/aru-software/as-wiki/as-wiki-ui:latest -t git.aru-software.pl/aru-software/as-wiki/as-wiki-ui:0.0.$BUILD_NUMBER .
                    docker login git.aru-software.pl -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
                    docker push git.aru-software.pl/aru-software/as-wiki/as-wiki-ui:latest
                    docker push git.aru-software.pl/aru-software/as-wiki/as-wiki-ui:0.0.$BUILD_NUMBER
            - name: SRV Docker Build
              run: |
                    cd server
                    docker build -t git.aru-software.pl/aru-software/as-wiki/as-wiki-srv:latest -t git.aru-software.pl/aru-software/as-wiki/as-wiki-srv:0.0.$BUILD_NUMBER .
                    docker login git.aru-software.pl -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
                    docker push git.aru-software.pl/aru-software/as-wiki/as-wiki-srv:latest
                    docker push git.aru-software.pl/aru-software/as-wiki/as-wiki-srv:0.0.$BUILD_NUMBER
