name: Build & Test
run-name: Build and test the asWiki app's UI and SRV
on:
    push:
        branches:
            - main
            - develop
    pull_request:
        types:
            - opened
            - synchronize

jobs:
    UI-Build-&-Test:
        runs-on: local-runner
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: |
                    . $NVM_DIR/nvm.sh
                    cd ui
                    nvm install
                    npm install
                    npm run eslint
                    npm run build
            - name: Test
              run: |
                    . $NVM_DIR/nvm.sh
                    cd ui
                    nvm install
                    npm run test
                    npm run test:coverage
    SRV-Build-&-Test:
        runs-on: local-runner
        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: |
                    . $NVM_DIR/nvm.sh
                    cd server
                    nvm install
                    npm install
                    npm run eslint
                    npm run build
