name: Test Action
run-name: ${{ gitea.actor }} is testing out Gitea Actions
on:
    push:
        branches:
            - main
            - develop
    pull_request:
        types:
            - opened

jobs:
    Node-Build-&-Test:
        runs-on: local-runner
        steps:
            - uses: actions/checkout@v3
            - name: UI Build
              env:
                  DB_USER: ${{ secrets.TEST_SERVICES_PG_USER }}
              run: |
                    . $NVM_DIR/nvm.sh
                    cd ui
                    nvm install
                    npm install
                    npm run eslint
                    npm run build
            - name: UI Test
              run: |
                    . $NVM_DIR/nvm.sh
                    cd ui
                    nvm install
                    npm run test
                    npm run test:coverage
            - name: SRV Build
              run: |
                    . $NVM_DIR/nvm.sh
                    cd server
                    nvm install
                    npm install
                    npm run eslint
                    npm run build
            - name: Check secrets
              run: |
                    echo "$DB_USER"
