name: Test Action
run-name: ${{ gitea.actor }} is testing out Gitea Actions
on: [push]

jobs:
    Check-NVM:
        runs-on: local-runner
        steps:
            - run: "source ~/.bashrc"
            - run: "nvm install"
            - run: "docker --version"