name: Test Action
run-name: ${{ gitea.actor }} is testing out Gitea Actions
on: [push]

jobs:
    Check-NVM:
        runs-on: local-runner:host
        steps:
            - run: "nvm --version"
            - run: "docker --version"