name: Build PROD Docker image
run-name: Build the asWiki app's PROD Docker image
on:
    workflow_run:
        workflows: ["Build & Test"]
        types:
            - completed
        branches:
            - main

jobs:
    PROD-Build-Docker:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        env:
            BUILD_NUMBER: ${{ github.run_number }}
            REGISTRY: ghcr.io
            IMAGE_NAME: ${{ github.repository }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: UI Docker Build
              run: |
                    cd ui
                    docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.REPOSITORY_TOKEN }}
                    docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui:latest -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui:0.0.$BUILD_NUMBER --push .
            - name: SRV Docker Build
              run: |
                    cd server
                    docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.REPOSITORY_TOKEN }}
                    docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-srv:latest -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-srv:0.0.$BUILD_NUMBER --push .
