name: Build DEV Docker image
run-name: Build the asWiki app's DEV Docker image
on:
    push:
        branches:
            - develop

jobs:
    DEV-Build-Docker:
        runs-on: ubuntu-latest
        container:
            image: 'docker:dind'
        permissions:
            contents: read
            packages: write
        env:
            BUILD_NUMBER: ${{ github.run_id }}
            REGISTRY: ghcr.io
            IMAGE_NAME: ${{ github.repository }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.REPOSITORY_TOKEN }}

            - name: Extract UI metadata for Docker
              id: meta_ui
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui

            - name: Build and push UI Docker image
              uses: docker/build-push-action@v5
              with:
                context: "{{defaultContext}}:ui"
                push: true
                tags: ${{ steps.meta_ui.outputs.tags }}
                labels: ${{ steps.meta_ui.outputs.labels }}

            - name: Extract UI metadata for Docker
              id: meta_srv
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-srv

            - name: Build and push UI Docker image
              uses: docker/build-push-action@v5
              with:
                context: "{{defaultContext}}:server"
                push: true
                tags: ${{ steps.meta_srv.outputs.tags }}
                labels: ${{ steps.meta_srv.outputs.labels }}s-wiki-srv:0.0.$BUILD_NUMBER-dev